sudo: required

language: c

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

before_install:
  - sudo apt-get install qemu-user-static
  - cp /usr/bin/qemu-s390x-static .
  - cp /usr/bin/qemu-hppa-static .
  - travis_wait 45 docker build -f Dockerfile.cross -t moxielogic/cross-ci-build-container .

script:
- 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      for ARCH in cross; do
        docker tag moxielogic/${ARCH}-ci-build-container:latest moxielogic/${ARCH}-ci-build-container:$COMMIT;
        docker push moxielogic/${ARCH}-ci-build-container:latest;
        docker push moxielogic/${ARCH}-ci-build-container:$COMMIT;
      done;
    fi
  - echo All done.
