sudo: required

language: c

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

before_install:
  - sudo apt-get install qemu-user-static
  - cp /usr/bin/qemu-arm-static .
  - cp /usr/bin/qemu-aarch64-static .
  - cp /usr/bin/qemu-ppc64le-static .
  - cp /usr/bin/qemu-s390x-static .
  - docker build -f Dockerfile.arm32v7 -t moxielogic/arm32v7-ci-build-container .
  - docker build -f Dockerfile.aarch64 -t moxielogic/aarch64-ci-build-container .
  - docker build -f Dockerfile.ppc64le -t moxielogic/ppc64le-ci-build-container .
  - docker build -f Dockerfile.s390x -t moxielogic/s390x-ci-build-container .

script:
- 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      for ARCH in arm32v7 aarch64 ppc64le s390x; do
        docker tag moxielogic/${ARCH}-ci-build-container:latest moxielogic/${ARCH}-ci-build-container:$COMMIT;
        docker push moxielogic/${ARCH}-ci-build-container:latest;
        docker push moxielogic/${ARCH}-ci-build-container:$COMMIT;
      done;
    fi
  - echo All done.
