sudo: required

language: c

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

before_install:
  - sudo apt-get install qemu-user-static
  - cp /usr/bin/qemu-aarch64-static .
  - travis_wait 45 docker build -f Dockerfile.aarch64 -t moxielogic/aarch64-ci-build-container .

# - cp /usr/bin/qemu-s390x-static .
# - cp /usr/bin/qemu-arm-static .
# This one takes too long
#  - travis_wait 45 docker build -f Dockerfile.s390x -t moxielogic/s390x-ci-build-container .

# ppc64le currently causes an illegal instruction error
#  - cp /usr/bin/qemu-ppc64le-static .
#  - docker build -f Dockerfile.ppc64le -t moxielogic/ppc64le-ci-build-container .

script:
- 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      for ARCH in aarch64; do
        docker tag moxielogic/${ARCH}-ci-build-container:latest moxielogic/${ARCH}-ci-build-container:$COMMIT;
        docker push moxielogic/${ARCH}-ci-build-container:latest;
        docker push moxielogic/${ARCH}-ci-build-container:$COMMIT;
      done;
    fi
  - echo All done.
